# Generated by Django 4.0.5 on 2022-06-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('expiry', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_quantity', models.IntegerField()),
                ('add_quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('date_of_manufacture', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_management.product')),
            ],
        ),
    ]
