# Generated by Django 4.0.5 on 2022-07-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sold',
            field=models.IntegerField(null=True),
        ),
    ]
