# Generated by Django 4.0.3 on 2022-04-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_management.product')),
            ],
        ),
    ]
