# Generated by Django 4.0.3 on 2022-04-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0006_oderdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderDetail',
            new_name='OrderDetail',
        ),
    ]
