# Generated by Django 4.0.3 on 2022-04-21 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0007_rename_oderdetail_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='creat_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='creat_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='creat_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='creat_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 34, 34, 206978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
