# Generated by Django 4.0.3 on 2022-04-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0008_customer_created_at_customer_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creat_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creat_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='creat_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='creat_by',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_by',
        ),
    ]
