# Generated by Django 4.0.3 on 2022-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_management', '0012_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.IntegerField(choices=[(0, 'FEMALE'), (1, 'MALE'), (2, 'UNKNOWN')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Accepted')], default=0),
        ),
    ]
